// <auto-generated />
using Mango.Services.Product.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.Product.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220831210637_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.Product.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Mango.Services.Product.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Appetizer",
                            Description = "asvawgawg  awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagva vawgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagvaawgawvagva",
                            ImageUrl = "https://gabimango.blob.core.windows.net/mango/14.jpg",
                            Name = "Samos",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Appetizer",
                            Description = "asvawgawg  awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagva vawgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagvaawgawvagva",
                            ImageUrl = "https://gabimango.blob.core.windows.net/mango/12.jpg",
                            Name = "Paneer Tikka",
                            Price = 16.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Desert",
                            Description = "asvawgawg  awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagva vawgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagvaawgawvagva",
                            ImageUrl = "https://gabimango.blob.core.windows.net/mango/11.jpg",
                            Name = "Sweet Pie",
                            Price = 17.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Entree",
                            Description = "asvawgawg  awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagva vawgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagva awgawvagvaawgawvagva awgawvagvaawgawvagva",
                            ImageUrl = "https://gabimango.blob.core.windows.net/mango/13.jpg",
                            Name = "Pav Bhaji",
                            Price = 20.0
                        });
                });

            modelBuilder.Entity("Mango.Services.Product.API.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Mango.Services.Product.API.Models.ProductCategory", b =>
                {
                    b.HasOne("Mango.Services.Product.API.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mango.Services.Product.API.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mango.Services.Product.API.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Mango.Services.Product.API.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
